version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: zapsign_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zapsign_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: zapsign_backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend/zapsign-frontend
    container_name: zapsign_frontend

    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  db_data:
